server:
  port: 8082
spring:
  application:
    name: spring-boot-mybatis-template
  mvc:
    async:
      request-timeout: 20000
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        allow: 127.0.0.1
        login-username: szeport
        login-password: szeport
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      click:
        driver-class-name: cc.blynk.clickhouse.ClickHouseDriver
        #url: jdbc:clickhouse://192.168.1.171:8123/macro_data
        url: jdbc:clickhouse://192.168.1.171:8123/macro_data_dev

        #        connectionProperties: config.decrypt=true;config.decrypt.key=${databaseKey.clickpublicKey};
        #        username: test
        #password: ToFf2efBy+98+Qznwnr+PVOiC3+0xK8RcHdmtG4L74Us7cS1R3KjLhnVelCgaU8iPGx3Qhmdlq51JYbn+UcDkw==
        #        password: OCjE4tDGJfvQRYlY/xzoQDVkiFltj2uIdZjCgn3/R9rhwps6uY/DDiMNJ/inUsdrWX5oDbEiI/Iq0i5mVaEZCw==
        username: develop
        password: develop
        initial-size: 50
        max-active: 100
        min-idle: 20
        max-wait: 60000
        validation-query: SELECT 1
        filters: config,slf4j
mybatis-plus:
  configuration:
    #    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.szeport.entity
#日志
logging:
  file: ./logs/log.log
  level:
    root: DEBUG